version: '3.8'
services:
  mysql-db:
    image: mysql:8.0.33
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345600
      MYSQL_DATABASE: StudentDB
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - springmysql

  spring-app:
    build: .
    container_name: spring-container
    ports:
      - "8082:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - springmysql

networks:
  springmysql:
    driver: bridge